### ISSUE TITLE
Terraform Infrastructure Setup

### ISSUE THREAD

**Issue by christoff-linde** [christoff-linde/pih-terraform#1]
## Description

To enable the creation/management of infrastructure, Terraform can be leveraged to help with this process.

Using Terraform (potentially Cloud, or here in GitHub) the required infrastructure can be provisioned.

## Planned Resources

The following services would be core to the PIH service:

- [ ] christoff-linde/pih-terraform#5
- [ ] christoff-linde/pih-terraform#4
- [ ] christoff-linde/pih-rs#71

The following services are still under investigation/consideration:

- AWS SQS/SNS
- AWS AppSync
- AWS ApiGateway
